trigger:
  branches:
    include:
      - develop
      - master

pool:
  name: 'CloudAgent'

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build Application'
  jobs:
  - job: BuildJob
    displayName: 'Build and Test'
    steps:
    - script: echo "Building the application... Branch is $(Build.SourceBranchName)"
      displayName: 'Build Information'

    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'
      displayName: 'Install .NET SDK'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
      displayName: 'Build .NET Application'

    # Debugging: List files after build (Fixed OS-specific commands)
    - script: |
        echo "Listing build output..."
        if exist C:\Windows\System32\cmd.exe (
            dir $(Build.SourcesDirectory)\bin\$(buildConfiguration)
        ) else (
            ls -la $(Build.SourcesDirectory)/bin/$(buildConfiguration)
        )
      displayName: 'Check Build Output Files'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/bin/$(buildConfiguration)'
        Contents: '**/*'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Copy Build Output to Artifact Staging'

    # Debugging: List files in artifact staging directory (Fixed OS-specific commands)
    - script: |
        echo "Listing artifact staging directory..."
        if exist C:\Windows\System32\cmd.exe (
            dir $(Build.ArtifactStagingDirectory)
        ) else (
            ls -la $(Build.ArtifactStagingDirectory)
        )
      displayName: 'Verify Artifact Staging Directory'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
      displayName: 'Publish Build Artifacts'

# Deploy to Development (Fixed Condition)
- stage: DeployToDev
  displayName: 'Deploy to Development'
  dependsOn: Build
  condition: or(eq(variables['Build.SourceBranchName'], 'develop'), eq(variables['Build.SourceBranchName'], 'master'))
  jobs:
  - deployment: DeployDev
    displayName: 'Deploy to Dev Environment'
    environment: 'Development'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(Pipeline.Workspace)/drop'
            displayName: 'Download Build Artifacts'

          - script: |
              echo "Listing deployment directory..."
              if exist C:\Windows\System32\cmd.exe (
                  dir $(Pipeline.Workspace)\drop
              ) else (
                  ls -la $(Pipeline.Workspace)/drop
              )
            displayName: 'Debug Deployment Files'

          - script: |
              echo "Starting deployment..."
              if exist C:\Windows\System32\cmd.exe (
                  echo "Deployment script is not configured for Windows!"
              ) else (
                  chmod +x $(Pipeline.Workspace)/drop/deploy_dev.sh
                  /bin/bash $(Pipeline.Workspace)/drop/deploy_dev.sh
              )
            displayName: 'Deploy to Development'
            failOnStderr: true

# Deploy to Production (Fixed Condition)
- stage: DeployToProd
  displayName: 'Deploy to Production'
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
  jobs:
  - deployment: DeployProd
    displayName: 'Deploy to Production Environment'
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(Pipeline.Workspace)/drop'
            displayName: 'Download Build Artifacts'

          - script: |
              echo "Listing deployment directory..."
              if exist C:\Windows\System32\cmd.exe (
                  dir $(Pipeline.Workspace)\drop
              ) else (
                  ls -la $(Pipeline.Workspace)/drop
              )
            displayName: 'Debug Deployment Files'

          - script: |
              echo "Starting deployment..."
              if exist C:\Windows\System32\cmd.exe (
                  echo "Deployment script is not configured for Windows!"
              ) else (
                  chmod +x $(Pipeline.Workspace)/drop/deploy_prod.sh
                  /bin/bash $(Pipeline.Workspace)/drop/deploy_prod.sh
              )
            displayName: 'Deploy to Production'
            failOnStderr: true
