trigger:
  branches:
    include:
      - develop
      - master

pool:
  name: 'CloudAgent'

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build Application'
  jobs:
  - job: BuildJob
    displayName: 'Build and Test'
    steps:
    - script: echo "Building the application... Branch is $(Build.SourceBranchName)"
      displayName: 'Build Information'
      
    # Your build steps here
    - script: echo "Packaging the application..."
      displayName: 'Package Application'
    
    # Copy build outputs to artifact staging directory
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.BinariesDirectory)'
        Contents: '**/*'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Copy Build Output to Artifact Staging'
    
    # Publish the artifact for use in deployment stages
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
      displayName: 'Publish Build Artifacts'

# Deploy to Development for develop and master branches
- stage: DeployToDev
  displayName: 'Deploy to Development'
  dependsOn: Build
  condition: or(eq(variables['Build.SourceBranchName'], 'develop'), eq(variables['Build.SourceBranchName'], 'master'))
  jobs:
  - deployment: DeployDev
    displayName: 'Deploy to Dev Environment'
    environment: 'Development'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
            displayName: 'Download Build Artifacts'
          
          - script: |
              echo "Deploying to development environment..."
              echo "Current branch: $(Build.SourceBranchName)"
              ./deploy_dev.sh  # Example deployment script
            displayName: 'Deploy to Development'

# Deploy to Production with manual approval ONLY for master branch
- stage: DeployToProd
  displayName: 'Deploy to Production'
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
  jobs:
  - deployment: DeployProd
    displayName: 'Deploy to Production Environment'
    environment: 'Production'  # This environment should have approval gates configured
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
            displayName: 'Download Build Artifacts'
          
          - script: |
              echo "Deploying to production environment..."
              echo "Current branch: $(Build.SourceBranchName)"
              ./deploy_prod.sh  # Example production deployment script
            displayName: 'Deploy to Production'
