trigger:
  branches:
    include:
      - develop
      - master

pool:
  name: 'CloudAgent'

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build Application'
  jobs:
  - job: BuildJob
    displayName: 'Build and Test'
    steps:
    - script: echo "Building the application... Branch is $(Build.SourceBranchName)"
      displayName: 'Build Information'
      
    # Your build steps here
    - script: echo "Packaging the application..."
      displayName: 'Package Application'
    
    # Copy build outputs to artifact staging directory
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.BinariesDirectory)'
        Contents: '**/*'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Copy Build Output to Artifact Staging'
    
    # Publish the artifact for use in deployment stages
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
      displayName: 'Publish Build Artifacts'

# Deploy to Development for develop and master branches
- stage: DeployToDev
  displayName: 'Deploy to Development'
  dependsOn: Build
  condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: DeployDev
    displayName: 'Deploy to Dev Environment'
    environment: 'Development'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(Pipeline.Workspace)/drop'
            displayName: 'Download Build Artifacts'

          - script: |
              echo "Listing deployment directory..."
              ls -la $(Pipeline.Workspace)/drop
              echo "Checking environment variables..."
              env
            displayName: 'Debug Deployment Files and Environment'

          - script: |
              echo "Converting script to Unix format..."
              /usr/bin/dos2unix $(Pipeline.Workspace)/drop/deploy_dev.sh || echo "dos2unix not found, skipping..."
              chmod +x $(Pipeline.Workspace)/drop/deploy_dev.sh
              echo "Starting deployment..."
              /bin/bash $(Pipeline.Workspace)/drop/deploy_dev.sh
            displayName: 'Deploy to Development'
            failOnStderr: true

# Deploy to Production with manual approval ONLY for master branch
- stage: DeployToProd
  displayName: 'Deploy to Production'
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: DeployProd
    displayName: 'Deploy to Production Environment'
    environment: 'Production'  # This environment should have approval gates configured
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(Pipeline.Workspace)/drop'
            displayName: 'Download Build Artifacts'
          
          - script: |
              echo "Listing deployment directory..."
              ls -la $(Pipeline.Workspace)/drop
              echo "Checking environment variables..."
              env
            displayName: 'Debug Deployment Files and Environment'

          - script: |
              echo "Converting script to Unix format..."
              /usr/bin/dos2unix $(Pipeline.Workspace)/drop/deploy_prod.sh || echo "dos2unix not found, skipping..."
              chmod +x $(Pipeline.Workspace)/drop/deploy_prod.sh
              echo "Starting deployment..."
              /bin/bash $(Pipeline.Workspace)/drop/deploy_prod.sh
            displayName: 'Deploy to Production'
            failOnStderr: true
