trigger:
  branches:
    include:
      - develop
      - master

pool:
  name: 'CloudAgent'

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build Application'
  jobs:
  - job: BuildJob
    displayName: 'Build and Test'
    steps:
    - script: echo "Building the application... Branch is $(Build.SourceBranchName)"
      displayName: 'Build Information'

    # Install .NET SDK
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'
      displayName: 'Install .NET SDK'

    # Build the .NET application
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
      displayName: 'Build .NET Application'

    # ✅ FIX: Check Build Output (Windows-Compatible)
    - script: |
        echo "Listing build output..."
        dir "$(Build.SourcesDirectory)\bin\$(buildConfiguration)" /s
      displayName: 'Check Build Output Files'

    # Copy build outputs to artifact staging directory
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)\bin\$(buildConfiguration)'
        Contents: '**/*'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Copy Build Output to Artifact Staging'

    # ✅ FIX: Check Artifact Staging (Windows-Compatible)
    - script: |
        echo "Listing artifact staging directory..."
        dir "$(Build.ArtifactStagingDirectory)" /s
      displayName: 'Verify Artifact Staging Directory'

    # Publish build artifacts
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
      displayName: 'Publish Build Artifacts'

# Deploy to Development
- stage: DeployToDev
  displayName: 'Deploy to Development'
  dependsOn: Build
  condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: DeployDev
    displayName: 'Deploy to Dev Environment'
    environment: 'Development'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(Pipeline.Workspace)/drop'
            displayName: 'Download Build Artifacts'

          # ✅ FIX: Windows-Compatible Debug Step
          - script: |
              echo "Listing deployment directory..."
              dir "$(Pipeline.Workspace)\drop" /s
            displayName: 'Debug Deployment Files'

          - script: |
              echo "Starting deployment..."
              powershell -ExecutionPolicy Bypass -File "$(Pipeline.Workspace)\drop\deploy_dev.ps1"
            displayName: 'Deploy to Development'
            failOnStderr: true

# Deploy to Production (Manual Approval)
- stage: DeployToProd
  displayName: 'Deploy to Production'
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - deployment: DeployProd
    displayName: 'Deploy to Production Environment'
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(Pipeline.Workspace)/drop'
            displayName: 'Download Build Artifacts'

          # ✅ FIX: Windows-Compatible Debug Step
          - script: |
              echo "Listing deployment directory..."
              dir "$(Pipeline.Workspace)\drop" /s
            displayName: 'Debug Deployment Files'

          - script: |
              echo "Starting deployment..."
              powershell -ExecutionPolicy Bypass -File "$(Pipeline.Workspace)\drop\deploy_prod.ps1"
            displayName: 'Deploy to Production'
            failOnStderr: true
